# Generated by Django 4.0.5 on 2022-09-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0002_alter_videosmodel_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videosmodel',
            unique_together={('title', 'description')},
        ),
    ]
