# Generated by Django 4.0.5 on 2022-09-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0004_alter_videosmodel_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosmodel',
            options={'ordering': ['-published_on']},
        ),
    ]
